# Generated by Django 3.1 on 2020-08-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200823_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Resumo do post', max_length=255),
        ),
    ]
